name: Build and Push Docker Image
on:
  push:
    tags:
      - "v*"

env:
  GITHUB_REGISTRY: ghcr.io/bkov96

jobs:
  build-docker:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.tagging.outputs.docker_tag }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Set Image Version Tag
      id: tagging
      run: echo "::set-output name=docker_tag::$GITHUB_REGISTRY/node-lunch-vulnerability:$GITHUB_REF_NAME"

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ env.GITHUB_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Docker Build
      run: |
        docker build -t ${{ steps.tagging.outputs.docker_tag }} .
    
    - name: Docker Push
      run: |
        docker push ${{ steps.tagging.outputs.docker_tag }}